name: iOS CI - Sanity Check Only

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sanity-check:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode 15.0.1
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app

      - name: Remove corrupted Package.resolved
        run: |
          find . -name "Package.resolved" -delete

      - name: Resolve Swift Packages
        run: |
          xcodebuild -resolvePackageDependencies -project WallaMarvel.xcodeproj || true
