name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Clean and delete corrupted Package.resolved
        run: |
          find . -name "Package.resolved" -delete

      - name: Build for Testing (Exclude arm64 for simulator)
        run: |
          xcodebuild build-for-testing \
            -scheme WallaMarvel \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.5' \
            -configuration Debug \
            ARCHS="x86_64" \
            EXCLUDED_ARCHS=arm64 \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      - name: Run Tests
        run: |
          xcodebuild test-without-building \
            -scheme WallaMarvel \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.5' \
            -configuration Debug \
            ARCHS="x86_64" \
            EXCLUDED_ARCHS=arm64 \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
