name: iOS CI - Build Only

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app

      - name: Remove corrupted Package.resolved (if exists)
        run: |
          find . -name "Package.resolved" -delete

      - name: Resolve Swift Packages
        run: |
          xcodebuild -resolvePackageDependencies -project WallaMarvel.xcodeproj

      - name: Build App Only
        run: |
          xcodebuild build \
            -scheme WallaMarvel \
            -project WallaMarvel.xcodeproj \
            -destination 'generic/platform=iOS Simulator' \
            -sdk iphonesimulator \
            CODE_SIGNING_ALLOWED=NO
