name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode 15.0.1
      run: sudo xcode-select -s /Applications/Xcode_15.0.1.app

    - name: Clean corrupted Package.resolved
      run: |
        echo "Removing corrupted Package.resolved..."
        rm -f WallaMarvel.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

    - name: Resolve Swift Package dependencies
      run: xcodebuild -resolvePackageDependencies

    - name: Build and Test
      run: |
        xcodebuild test \
          -scheme WallaMarvel \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' \
          -enableCodeCoverage YES
