name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Xcode version (15.3)
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Clean and reset
        run: |
          rm -rf DerivedData
          find . -name "Package.resolved" -delete

      - name: Build and test (Simulator - iPhone 14)
        run: |
          xcodebuild test \
            -scheme WallaMarvel \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.5' \
            -sdk iphonesimulator \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=NO \
            EXCLUDED_ARCHS="arm64"
