name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select Xcode 15.0.1
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app

      - name: Delete corrupted Package.resolved
        run: |
          find . -name "Package.resolved" -delete

      - name: Resolve SPM dependencies
        run: |
          xcodebuild -resolvePackageDependencies

      - name: Build the app
        run: |
          xcodebuild build-for-testing \
            -scheme WallaMarvel \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone SE (3rd generation),OS=17.2' \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      - name: Run Unit and UI Tests
        run: |
          xcodebuild test-without-building \
            -scheme WallaMarvel \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone SE (3rd generation),OS=17.2' \
            -configuration Debug \
            -enableCodeCoverage YES \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
